### PR TITLE
fix(triage): declare the customer-bug destination and stop auto-creating Domains (#421)

### LINKED ISSUE #421: [Illo-QA][triage] Customer-bug intake has no defined destination — a new Domain was auto-created and no GitHub issue was ever filed
> From the 2026-07-22 customer-bug intake incident.

## Problem

Customer-bug intake has **no defined destination**, so identical requests land in different systems from one run to the next. Asked to *"assign ticket to me"* for a customer email, Illo **created a brand-new Domain 42 `customer-support-tickets`** and filed record 2383 into it — and never created a GitHub issue. When the human then asked *"and the github ticket?"*, there was none, and none exists now.

The record itself is good — `type: bug`, `priority: high`, `status: triaging`, `assignee_name: Reda`, a real impact line (*"Potential billing/credit integrity issue; should be treated as high priority until credits and job state are checked"*), `origin_ref` back to the Slack message. It is simply in a tracker nobody reads, created seconds earlier, while every comparable request in the same 24 hours produced a GitHub issue:

| Request | Destination |
|---|---|
| Killtec API-docs email (2026-07-21 14:30 ET) | `uwear-backend#1186` + tracker record 2263 |
| Retool ivory-button complaint (2026-07-21 21:43 ET) | `uwear-backend#1203` |
| Gemini 3.6 (2026-07-22 06:46 ET) | `uwear-backend#1209` |
| **Emily / 99% + credits (2026-07-22 13:41 ET)** | **new Domain 42, record 2383, no GitHub issue** |

Verified: `gh issue list` across `uwear-ai/uwear-backend` and `uwear-ai/uwearaiapp` returns **no** issue for this customer bug.

This directly undercuts the one-shared-object principle: spinning up a private tracker mid-request fragments coordination rather than concentrating it, and the human cannot find the work where they expect it.

Contributing detail worth fixing on the way past: the run first hit `manage_domain failed — field_type must be one of: boolean, date, datetime, email, enum, json, long_text, money, multi_enum, number, phone, reco…`, then created the new domain on the retry. Schema-creation was attempted inline, mid-request, for what should have been a filing operation.

## Proposed fix

1. **Declare the destination for customer-reported bugs** and follow it: a GitHub issue in the owning repo is the durable artifact; the workspace tracker record is the mirror, not the substitute. Match the Killtec/Retool/Gemini path.
2. **Never create a Domain as a side effect of filing.** Creating a new tracker is a schema change: propose it, don't auto-create it — the same rule chantiers already follow (*"only propose, never auto-create"*).
3. **When the request names an artifact type** ("ticket", "issue"), produce that artifact or say explicitly why it could not be produced. Do not silently substitute a different artifact and report success.
4. Backfill: file the GitHub issue for this customer report (generations stuck at 99%, disappearing, credits still consumed — a billing-integrity issue), assign Reda, and link record 2383 to it.

## Acceptance checks

1. A Slack request to file a customer bug produces a GitHub issue in the owning repo **plus** a linked tracker record — never a tracker record alone.
2. Filing never creates a new Domain; if no suitable Domain exists, the run proposes one and files to the existing default meanwhile.
3. Replaying the Emily request produces a GitHub issue assigned to Reda whose body carries the customer quote, the credit-loss impact, and the Slack `origin_ref`.
4. When a requested artifact cannot be created, the reply names the artifact and the blocker — no silent substitution.

### PR DESCRIPTION
**Pull request by redawear**
Closes #421

## What was broken

Asked to *"assign ticket to me"* for a customer email, Illo **created a brand-new Domain 42 `customer-support-tickets`**, filed record 2383 into it, and never created a GitHub issue. When the human asked *"and the github ticket?"*, there was none — and as of this PR there still is none. Every comparable request in the same 24 hours (Killtec, Retool, Gemini) produced a GitHub issue in the owning repo.

Customer-bug intake had **no declared destination**, so identical requests landed in different systems run to run. Spinning up a private tracker mid-request fragments coordination instead of concentrating it, and the human cannot find the work where they expect it.

## What this changes

1. **The destination is declared and enforced** — a customer bug produces a GitHub issue in the owning repo, and the tracker record is its *mirror*, not a substitute.
2. **Filing never creates a Domain.** `create_domain` returns a **proposal** unless `confirm_schema_change=true`; a run with nowhere to file uses the existing default tracker and proposes the new Domain instead of conjuring one mid-request.
3. **The trigger that caused it is fixed too** — the run first hit `manage_domain failed — field_type must be one of: …` and created the Domain on the retry. Unsupported field types now return a typed `invalid_field_type` error naming the allowed values.
4. **No silent substitution** — a reply that swaps a tracker record for a requested GitHub issue, or omits the blocker, is rejected.

## How to judge this without reading the diff

```bash
cd /Users/redamjahed/Documents/UwearDev/.codex-worktrees/illospace-421-fix1
venv/bin/python -m pytest tests/test_agent.py tests/test_domains_service.py tests/test_builtin_skill_suite.py tests/test_create_github_issue_tool.py tests/test_architecture_boundaries.py tests/test_agent_runtime_modules.py -q
```

**252 passed** — I ran this myself, not just the worker.

### Acceptance checks
- [x] A customer-bug filing request produces a GitHub issue **plus** a linked tracker record — never a record alone.
- [x] Filing never creates a new Domain; it proposes one and files to the existing default meanwhile.
- [x] A requested artifact that cannot be created is named in the reply along with its blocker.
- [ ] **Not done here — needs you (see below):** the ticket's item 4, backfilling the real GitHub issue for the Emily report.

---

## ⚠️ The thing worth your attention

**The first version of this PR quietly reversed one of your past decisions, and I sent it back.**

Commit `4f27d59` — *"Make final-reply checker advisory instead of a hard gate"* — removed an unappealable checker veto **on purpose**, because it "bounced complete answers and forced guess-and-retry loops," and removed the escape hatch along with it. The first implementation of this ticket brought a hard veto back **without** the escape hatch. I verified the consequence in the code rather than assuming it: there was **no cap** on repeated `cortex_reply` blocks, so a false positive would make the run retry until it hit its global limit — exactly the loop that commit existed to kill. The trigger was wide too: a bare mention of "email" or "credits" armed it.

Independently, the maintainability review flagged the same code from a different angle — the policy was reverse-parsing structured tool results out of **truncated rendered prompt text** with regexes, hardcoding `domain_id == 1`, and hiding the blocking behavior behind a magic `override` string. The `sort_keys` removal existed only to keep JSON fragments ahead of the truncation budget.

Both were folded into commit 2:

- Deterministic policies now consume a typed `FinalReplyEvidence` / `ToolResultEvidence`; only the LLM prompt consumes rendered text. The regex probing is gone, `sort_keys=True` is restored, and `DEFAULT_TRACKER_DOMAIN_ID` replaces the magic constant.
- The magic `override` string is a typed `FinalReplyEnforcement` disposition.
- **The veto is bounded** — at most 2 artifact-contract blocks per run, then it degrades to the existing advisory warning. A contract gate cannot livelock a run.
- **The veto is escapable** — an artifact that was *attempted and failed*, named honestly in the reply with its blocker, is accepted. The rule stops silent substitution; it does not demand impossible work.

**Why I believe this is compatible with `4f27d59` rather than a quiet re-litigation of it:** that commit removed a *general, unappealable, LLM-judged* veto over any unresolved reply. What remains here is a *narrow, deterministic, evidence-backed* check that fires only when a specifically requested artifact is silently swapped for another — and it is capped and escapable, so it can never become the guess-and-retry gate. **If you disagree with that reading, this is the part to push back on** — it is a judgement call about a decision you made, not a detail.

**2 SHOULD-FIX deferred to #427:** Uwear filing choreography leaked into the globally visible `create_github_issue` definition (and is now restated in four places), and the ~356-line `_handle_manage_domain` dispatcher maintaining its contract in four parallel representations.

## Still needs you: the actual customer bug is filed nowhere

This PR stops the *mechanism* from recurring. It does not file the report that went missing. I confirmed there is still **no** issue in `uwear-ai/uwear-backend` or `uwear-ai/uwearaiapp` for Emily's report (generations stick at 99%, disappear, credits still consumed — a billing-integrity issue, first reported 2026-07-22 13:41 ET). Filing it is a live write to a production repo, which is outside what R3 may do on its own. Say the word and it gets filed with the customer quote, the credit-loss impact, the Slack `origin_ref`, and you as assignee.

### CODE REVIEW

**Comment by redawear** [comment]
**R3 (routine): pre-resolved the #430 collision so this PR needs no manual conflict resolution.**

`illo-qa/419-manage-idea-uuid-and-breaker-fix1` (PR #430) is now merged into this branch. Why: a pairwise merge simulation showed #430 and #431 both restructure the same function in `brain/systems/runs/direct_loop/tool_execution.py` (4 conflict hunks), and **a naive resolution silently reverts one of the two fixes**:

- taking #430's side drops `result_value` → `ToolResultEvidence.capture` falls back to stringified preview text, defeating this PR's structured-evidence fix;
- taking #431's side drops `error_class` → `direct_loop/loop_control.py`'s circuit breaker never fires, re-opening the 26-consecutive-failures bug #419 exists to fix.

Resolution keeps both. #430's extracted `_resolved_tool_result`/`_failed_tool_result` helpers are retained and now also populate `result_value`; the timeout path sets both fields; the recent-results block takes this PR's `ToolResultEvidence.capture(...)`, dropping #430's `recent_result["error_class"]` deliberately (`ToolResultEvidence` has no such field and nothing read it from that list — verified).

Verified: a Codex pass independently confirmed all six resolution claims; 401 passed on the union of both PRs' suites, 3996 passed on the full non-Docker suite (the 14 remaining are a broken local torch install and denied socket binds — both reproduce on clean `main`). Added a regression guard, mutation-tested in both directions so a future careless resolution fails loudly.

**Merge order:** #429 and #433 are independent — any order. Merge **#430 before this PR**; once #430 lands, this PR's diff narrows back to its own changes and merges clean.

**Comment by redawear** [comment]
## Conflict resolved — this PR is mergeable again (R3, 2026-07-23)

The merge train (#429/#430/#433/#435/#439) landing at ~09:55 ET turned this PR `CONFLICTING`. Resolved via a **fast-forward merge commit** (`649ff5a`) — no force-push, no history rewrite.

**The collision:** #430's typed tool-failure work and this branch's triage change both edit `direct_loop/tool_execution.py`. Two files conflicted: `tool_execution.py` (4 hunks) and `tests/test_tool_execution.py` (add/add).

**How it was resolved:**
- **Three additive hunks** — `ResolvedToolCall` now carries the **union**: `error_class` (#430) *plus* `result_content` and `result_value` (this branch). Neither side was dropped.
- **The one real design collision** (`recent_tool_results`): this branch appends `ToolResultEvidence.capture(...)` objects; main appended a truncated preview dict. Kept the evidence objects, because `FinalReplyEvidence.from_agent_context()` and `final_reply_checker` consume its structured `arguments`/`result`, which the preview shape discards.
  ⚠️ **This does not weaken #430's 3-strike breaker.** `LoopControlPolicy.observe_tool_result()` reads `error_class` off the `ResolvedToolCall` dataclass directly (`loop_control.py:100`), not out of `recent_tool_results` — verified before resolving, since silently breaking a shipped incident fix was the main risk here.
- **Test file** = union of both suites (add/add conflict).

**One thing worth flagging:** git's auto-merge silently produced a **duplicate `ToolExecutionResult` class declaration**. Both parents declare it exactly once; the differing fields above it made git treat the identical block as an independent addition on each side, so it produced two — with no conflict marker to notice. Byte-identical, so harmless at runtime, but it was merge damage rather than pre-existing code and has been removed.

**Verification on the merged tree** (outside the CI sandbox):
```
python -m pytest -q --ignore=tests/test_gpu_server.py --ignore=tests/test_llm_worker.py
→ 3990 passed, 76 skipped, 0 failed
```
The two ignored suites fail on a broken local `torch` install and fail identically on a clean `main`.

Still a draft — not marking ready or merging. Landing this unblocks #427, #420, #436, #438 and #428, which are all held on it.
